-- LISTE DES DÉPUTÉS — 15ème Législature
-- Source : Secrétariat Général de l'Assemblée Nationale
-- IMPORTANT : Pas de numéros de téléphone

-- Vider la table existante
DELETE FROM deputes;

-- Insérer les 151 députés réels
INSERT INTO deputes (num, name, constituency, department, groupe, photo_url, active) VALUES
(1,  'AKOUALA GAMBOU Francis Rivelin',        'Ouenzé 1',                'Brazzaville',    'CLUB 2002 P.U.R',  NULL,  true),
(2,  'AMBETO Blaise',                          'Ngoko',                   'Sangha',         'PCT',              NULL,  true),
(3,  'ANDOMOUI Raphaël',                       'Mpouya',                  'Plateaux',       'PCT',              NULL,  true),
(4,  'AYESSA ITOUA Claude-Aimé',               'Makélékélé 4',            'Brazzaville',    'Indépendant',      NULL,  true),
(5,  'AYO Mizere Davin',                       'Mbama',                   'Cuvette',        'PCT',              NULL,  true),
(6,  'BADIABIO Joseph',                        'Makélékélé 2',            'Brazzaville',    'UDH-YUKI',         NULL,  true),
(7,  'BAHAMBOULA Prince Bertrand',             'Mayama',                  'Pool',           'PCT',              NULL,  true),
(8,  'BAMBI GOMA Gérald Lone',                 'Makélékélé 1',            'Brazzaville',    'UDH-YUKI',         NULL,  true),
(9,  'BANIAKINA Antoine',                      'Ngoyo',                   'Pointe-Noire',   'PCT',              NULL,  true),
(10, 'BANTSIMBA Dieudonné',                    'Mfilou Ngamaba 2',        'Brazzaville',    'PCT',              NULL,  true),
(11, 'BATI Benoit',                            'District de Tsiaki',      'Bouenza',        'PCT',              NULL,  true),
(12, 'BAYENDISSA Brice Dimitri',               'Tié-Tié 2',               'Pointe-Noire',   'PCT',              NULL,  true),
(13, 'BAZOKOTO KABA Jacob Paulin',             'Mindouli 1',              'Pool',           'PCT',              NULL,  true),
(14, 'BIDIE BIA-MBEMBA Elbe Biscay',           'Louingui',                'Pool',           'RC',               NULL,  true),
(15, 'BIDOUNGA Alphonse',                      'Nkayi 1',                 'Bouenza',        'UPADS',            NULL,  true),
(16, 'BINDOULA MILANDOU Auguste',              'Mbandza-Ndounga',         'Pool',           'A.P.C',            NULL,  true),
(17, 'BISSOUTA MABOUNDA Aloyse Devic',         'Lumumba 2',               'Brazzaville',    'PCT',              NULL,  true),
(18, 'BITSAMINA Silvère',                      'Komono',                  'Lékoumou',       'Indépendant',      NULL,  true),
(19, 'BOBRO née KOUMBA Yacine Mfouma',         'Banda',                   'Likouala',       'PCT',              NULL,  true),
(20, 'BOCKO Martinien Régis Ulrich',           'Bacongo 2',               'Brazzaville',    'MCDDI',            NULL,  true),
(21, 'BOKAMBISSA Prudent',                     'Mossaka 1',               'Cuvette',        'PCT',              NULL,  true),
(22, 'BOKILO Rick Gerald',                     'Poto-Poto 1',             'Brazzaville',    'PCT',              NULL,  true),
(23, 'BOKOLOJOUE Antoine',                     'Kimba',                   'Plateaux',       'Indépendant',      NULL,  true),
(24, 'BOKOUMAKA Gabriel',                      'Bokoma',                  'Cuvette',        'PCT',              NULL,  true),
(25, 'BONGO Emilon Patrick',                   'Mvou-Mvou 1',             'Pointe-Noire',   'RDPS',             NULL,  true),
(26, 'BONGO-SAMBY née IBOMBO Louise',          'Owando District',         'Cuvette',        'PCT',              NULL,  true),
(27, 'BOUITI-VIAUDO Roland',                   'District de Loango',      'Kouilou',        'MAR',              NULL,  true),
(28, 'BOSSA Fidèle',                           'Ollombo 1',               'Plateaux',       'PCT',              NULL,  true),
(29, 'CHISSO Adelaïde Rufine',                 'District de Pikounda',    'Sangha',         'PCT',              NULL,  true),
(30, 'DAMBA NGOLO Octave',                     'Moungali 2',              'Brazzaville',    'PCT',              NULL,  true),
(31, 'DILOU NGOMA Samuel',                     'Nkayi 2',                 'Bouenza',        'PCT',              NULL,  true),
(32, 'DJOMBO Henri',                           'Enyele',                  'Likouala',       'PCT',              NULL,  true),
(33, 'DOLAMA Virginie Euphrasie',              'Impfondo District',       'Likouala',       'PCT',              NULL,  true),
(34, 'DOUKAGA Destinée Hermella',              'Nyanga',                  'Niari',          'PCT',              NULL,  true),
(35, 'DZAMBA Bienvenu Victor',                 'Kibangou',                'Niari',          'UPADS',            NULL,  true),
(36, 'ELENGA Faustin',                         'Talangaï 4',              'Brazzaville',    'PCT',              NULL,  true),
(37, 'ENGONDZO Brigida Jumael',                'Loukolela',               'Cuvette',        'PCT',              NULL,  true),
(38, 'ENGOUALI Bernard',                       'Ewo District',            'Cuvette-Ouest',  'PCT',              NULL,  true),
(39, 'ENKO MBALAWA Ernest Vianney',            'Ignie',                   'Sangha',         'PCT',              NULL,  true),
(40, 'ETOU Paul Carroph',                      'Gamboma 1',               'Plateaux',       'PCT',              NULL,  true),
(41, 'EYOBELE Gracia Desmet Dorel',            'Tchikapika',              'Plateaux',       'PCT',              NULL,  true),
(42, 'GANTSELE Alphonse',                      'Mbon',                    'Cuvette-Ouest',  'PCT',              NULL,  true),
(43, 'GASSACKYS Ferréol Constant Patrick',     'Poto-Poto 3',             'Brazzaville',    'PCT',              NULL,  true),
(44, 'GAVET Juste Bernardin',                  'Yaya',                    'Lékoumou',       'PCT',              NULL,  true),
(45, 'GAYAMA AHISSOU Esther',                  'Île Mbamou',              'Pool',           'PCT',              NULL,  true),
(46, 'GONDZIA Guy Patrick',                    'Dongou',                  'Likouala',       'PCT',              NULL,  true),
(47, 'GONGARAD NKOUA Eric',                    'Ngo',                     'Plateaux',       'UPDP',             NULL,  true),
(48, 'GOUAMBA Ninon Pachel',                   'Ouenzé 4',                'Brazzaville',    'PCT',              NULL,  true),
(49, 'GOUEMO-GOUEMO née MOUKALA Barbe',        'Dolisie 2',               'Niari',          'UPADS',            NULL,  true),
(50, 'GUIMBI Michel',                          'Kimongo',                 'Niari',          'PCT',              NULL,  true),
(51, 'HOBIE Thierry',                          'District de Kellé',       'Cuvette-Ouest',  'PCT',              NULL,  true),
(52, 'IBOVI Jean Claude',                      'Talangaï 2',              'Brazzaville',    'MDP',              NULL,  true),
(53, 'IKEMO Théodore',                         'Ntokou',                  'Cuvette',        'PCT',              NULL,  true),
(54, 'IKIEMI Constant Bruno Serges',           'Oyo District',            'Cuvette',        'PCT',              NULL,  true),
(55, 'ILLOYE-GOUYA Daniel',                    'Ouenzé 2',                'Brazzaville',    'PCT',              NULL,  true),
(56, 'KABA-VELE née MPAN Suzanne',             'Loandjili 1',             'Pointe-Noire',   'PCT',              NULL,  true),
(57, 'KAKY Léonce Alban Oscar',                'Makélékélé 3',            'Brazzaville',    'Indépendant',      NULL,  true),
(58, 'KALLA Marcel',                           'District de Mabombo',     'Sangha',         'PCT',              NULL,  true),
(59, 'KANDO Jean François',                    'Mongo-Mpoukou',           'Pool',           'PCT',              NULL,  true),
(60, 'KANGA Jean Bruno',                       'Liranga',                 'Likouala',       'PCT',              NULL,  true),
(61, 'KIBA Jean Paul',                         'Ollombo 2',               'Plateaux',       'PCT',              NULL,  true),
(62, 'KIGNOUMBI KIA MBOUNGOU Joseph',          'Sibiti District',         'Lékoumou',       'La Chaîne',        NULL,  true),
(63, 'KINZENZE Charles',                       'Mindouli 2',              'Pool',           'PCT',              NULL,  true),
(64, 'KOLELAS NTOUMI Juste Aurélien',          'Kinkala District',        'Pool',           'UDH-YUKI',         NULL,  true),
(65, 'KOUKA Jean',                             'District de Kayes',       'Niari',          'PCT',              NULL,  true),
(66, 'KOULA MIKIELEKO Fleury Edgard',          'Sembé',                   'Sangha',         'PCT',              NULL,  true),
(67, 'KOULOUMBOU Marie Jeanne',                'Boko',                    'Pool',           'PCT',              NULL,  true),
(68, 'LALISSINI BIKINDOU Justice Jerslin',     'Moutamba',                'Niari',          'PCT',              NULL,  true),
(69, 'LEKOUNDZOU Tsatsa Avanke',               'Boundji',                 'Cuvette',        'PCT',              NULL,  true),
(70, 'LEYINDA Pascal Alain',                   'Mayoko',                  'Niari',          'UPADS',            NULL,  true),
(71, 'LENGA Isidore',                          'Talangaï 5',              'Brazzaville',    'PCT',              NULL,  true),
(72, 'LISSOUBA Jérémy Sylvain Mehdi',          'Dolisie 1',               'Niari',          'UPADS',            NULL,  true),
(73, 'LOUSSILAHO MADZOKO Paul Florent',        'Loumo',                   'Niari',          'PCT',              NULL,  true),
(74, 'LOUVOUNOU Alphonse',                     'Mvouti 2',                'Kouilou',        'PCT',              NULL,  true),
(75, 'MABIALA Alexandre',                      'Kakamoeka',               'Kouilou',        'PCT',              NULL,  true),
(76, 'MABITA Jean Claude Stéphane',            'Moungoundou-Sud',         'Niari',          'MCDDI',            NULL,  true),
(77, 'MAKASSELA EWHAKOU Herdy Chryster',       'Epena 2',                 'Likouala',       'PCT',              NULL,  true),
(78, 'MAKOSSO Christian Ernest',               'Tchiamba-Nzassi',         'Kouilou',        'PCT',              NULL,  true),
(79, 'MAKOSSO Serge Marvelh',                  'Madingo-Kayes',           'Kouilou',        'MAR',              NULL,  true),
(80, 'MALONGA Nicolas Jean Jacques Frédéric',  'Madibou',                 'Brazzaville',    'UDH-YUKI',         NULL,  true),
(81, 'MALONGA Jean Paul',                      'Kinkala Commune',         'Pool',           'PRL',              NULL,  true),
(82, 'MAMONA Ferdinand',                       'Loandjili 2',             'Pointe-Noire',   'PCT',              NULL,  true),
(83, 'MATOMBE Paul',                           'Mvouti 1',                'Kouilou',        'PCT',              NULL,  true),
(84, 'MATSIMA BIAYENDA Antignac Patience',     'Vindza',                  'Pool',           'UDH-YUKI',         NULL,  true),
(85, 'MATSIMA KIMBEMBE Préférence Gérald',     'Bacongo 1',               'Brazzaville',    'UDH-YUKI',         NULL,  true),
(86, 'MAVOUNGOU Jean Aimé',                    'Louvakou',                'Niari',          'PCT',              NULL,  true),
(87, 'MAVOUNGOU Maurice',                      'Lumumba 3',               'Brazzaville',    'MAR',              NULL,  true),
(88, 'MBAMA Norbert',                          'Talangaï 1',              'Brazzaville',    'PCT',              NULL,  true),
(89, 'MBANI Marcel',                           'District de Zanaga',      'Lékoumou',       'PCT',              NULL,  true),
(90, 'MBANZOULOU Eugène',                      'Boko-Songho',             'Pool',           'PCT',              NULL,  true),
(91, 'MBOSSA Joseph',                          'Abala',                   'Plateaux',       'PCT',              NULL,  true),
(92, 'MBOUMA Albert',                          'Pokola',                  'Sangha',         'PCT',              NULL,  true),
(93, 'MEDOUZEL EDEB Serge Roselin',            'District de Ngbala',      'Likouala',       'PCT',              NULL,  true),
(94, 'MFALI Mathurin',                         'Ewo Commune',             'Cuvette-Ouest',  'PCT',              NULL,  true),
(95, 'MISSATOU Louis Gabriel Leuisel',         'Lumumba 1',               'Brazzaville',    'CLUB 2002 PUR',    NULL,  true),
(96, 'MOBONDZO ENDZONGA Marien',               'Mossaka 2',               'Cuvette',        'PCT',              NULL,  true),
(97, 'MOKA Alain',                             'Impfondo Commune',        'Likouala',       'PCT',              NULL,  true),
(98, 'MOUAGNI Aimé Hydevert',                  'Moungali 1',              'Brazzaville',    'CPR',              NULL,  true),
(99, 'MOUANDZA Pierre',                        'Mbinda',                  'Niari',          'PCT',              NULL,  true),
(100,'MOUHOUMOUNOU Davy Benoît',               'Mayeye',                  'Pool',           'PCT',              NULL,  true),
(101,'MOUNDELE-NGOLLO EHOUROSSIA Yves F.',     'Ongogni',                 'Plateaux',       'PCT',              NULL,  true),
(102,'MOUNEA DIZANGUE AYA Gervine Mauger',     'Moungali 3',              'Brazzaville',    'PRL',              NULL,  true),
(103,'MOUNGONDO Albert',                       'Madingou Commune',        'Bouenza',        'UPADS',            NULL,  true),
(104,'MUNARI née MABONDZOT Claudine',          'Mouyondzi',               'Bouenza',        'MUST',             NULL,  true),
(105,'MVOUBA Isidore',                         'Kindamba',                'Pool',           'PCT',              NULL,  true),
(106,'NDINGA-MAKANDA Accel Arnaud',            'Ouesso 1',                'Sangha',         'PCT',              NULL,  true),
(107,'NDOUMANGOYI Anicet',                     'Moungoundou Nord',        'Niari',          'URDC',             NULL,  true),
(108,'NDOUNA François',                        'Mossendjo 1',             'Niari',          'PCT',              NULL,  true),
(109,'NGABELET Auguste',                       'Madingou District',       'Bouenza',        'PCT',              NULL,  true),
(110,'NGAMBILI IBAM Bersol Exaucé',            'Djiri 2',                 'Brazzaville',    'PCT',              NULL,  true),
(111,'NGANONGO Paul',                          'District de Ngabé',       'Pool',           'PCT',              NULL,  true),
(112,'N''GOMA MBOUKOU Ulriche',               'District de Yamba',       'Likouala',       'PCT',              NULL,  true),
(113,'NGOUALA Antoine',                        'Londela-Kayes',           'Niari',          'PCT',              NULL,  true),
(114,'NGOULIFACE Boniface',                    'Djambala District',       'Plateaux',       'DRD',              NULL,  true),
(115,'N''KAZI Didier',                        'Goma Tsé-Tsé',            'Pool',           'DRD',              NULL,  true),
(116,'NKODIA KIND Gaétan',                     'Tié-Tié 1',               'Pointe-Noire',   'PCT',              NULL,  true),
(117,'NKOUKA née MAGANGA-YOGO Marianne',       'Divénié',                 'Niari',          'PCT',              NULL,  true),
(118,'NKOUKOULI Norbert',                      'Djambala 1',              'Plateaux',       'PCT',              NULL,  true),
(119,'NTSAMBA Léon Logan',                     'Makabana',                'Niari',          'PCT',              NULL,  true),
(120,'NTSIBA NGOULOUBI Melly Florent',         'Lékana',                  'Plateaux',       'PCT',              NULL,  true),
(121,'NZOMONO Macaire',                        'Mfouati',                 'Bouenza',        'PCT',              NULL,  true),
(122,'OBAM''ONDON Antoine Bienaimé',          'Gamboma 2',               'Plateaux',       'PCT',              NULL,  true),
(123,'OBAMBI Pierre',                          'Talangaï 3',              'Brazzaville',    'PCT',              NULL,  true),
(124,'OKOKO née DOUKORO Angèle',               'Ouesso 2',                'Sangha',         'PCT',              NULL,  true),
(125,'OKOUENI Michel',                         'District de Kabo',        'Sangha',         'PCT',              NULL,  true),
(126,'OMVOUELET Francis Pépin',                'Etoumbi',                 'Cuvette-Ouest',  'PCT',              NULL,  true),
(127,'ONDZE née NGAMBOLO Bernadette',          'Makotipoko',              'Plateaux',       'PCT',              NULL,  true),
(128,'OPENDZOBE Fulgence',                     'Mokeko',                  'Sangha',         'PCT',              NULL,  true),
(129,'OPIMBAT Léon Alfred',                    'Mbomo',                   'Cuvette-Ouest',  'PCT',              NULL,  true),
(130,'OPIMBAT née MBOUNDZA MOKE EBOTIKAMBI Charlotte', 'Poto-Poto 2',    'Brazzaville',    'PCT',              NULL,  true),
(131,'OSSEBI Jean Christian',                  'Allembe',                 'Plateaux',       'PCT',              NULL,  true),
(132,'OTSALEYOUA Saturnin',                    'Okoyo',                   'Cuvette-Ouest',  'PCT',              NULL,  true),
(133,'OWASSA YAUCKA Abel Joël',                'Owando Commune',          'Cuvette',        'PCT',              NULL,  true),
(134,'OYO EMBOUNOU Romarick Jules Junior',     'Ouenzé 3',                'Brazzaville',    'PCT',              NULL,  true),
(135,'POUOMOUO Albert',                        'Sibiti',                  'Lékoumou',       'PCT',              NULL,  true),
(136,'SABAYE Fernand',                         'Betou',                   'Likouala',       'PCT',              NULL,  true),
(137,'SAMBA Sylvain',                          'Mfilou 1',                'Brazzaville',    'UDH-YUKI',         NULL,  true),
(138,'SASSOU N''GUESSO Stella',               'Kintélé Commune',         'Brazzaville',    'PCT',              NULL,  true),
(139,'SEKO Hyppolite',                         'Bouanela',                'Bouenza',        'PCT',              NULL,  true),
(140,'SIBALY Jean',                            'Kingoué',                 'Bouenza',        'PCT',              NULL,  true),
(141,'SITOU Jean Baptiste',                    'Nzambi',                  'Kouilou',        'MAR',              NULL,  true),
(142,'SOUAKA Judes Wilfride',                  'Bambama',                 'Lékoumou',       'Indépendant',      NULL,  true),
(143,'SOUNDA Jean Aimé',                       'Hinda',                   'Kouilou',        'RDPS',             NULL,  true),
(144,'TCHIGNOUMBA BOUMBA Gilbert Paul',        'Mvou-Mvou 2',             'Pointe-Noire',   'PCT',              NULL,  true),
(145,'TIELE GAMBIA OLOU Antoinette',           'Djiri 1',                 'Brazzaville',    'PCT',              NULL,  true),
(146,'TONO Marie Louise',                      'Epena 1',                 'Likouala',       'PCT',              NULL,  true),
(147,'TSATY-MABIALA Pascal',                   'Loudima',                 'Bouenza',        'UPADS',            NULL,  true),
(148,'TSOUMOU Yves',                           'Mossendjo 2',             'Niari',          'PCT',              NULL,  true),
(149,'YEKA Frédéric',                          'Makoua',                  'Cuvette',        'PCT',              NULL,  true),
(150,'YOKA Justin',                            'Oyo 1',                   'Cuvette',        'PCT',              NULL,  true),
(151,'ZONIABA AYIMESSONE Henri',               'Souanké',                 'Sangha',         'PCT',              NULL,  true);
